#!/usr/bin/env python3
"""Generate subordinate machine-readable views from the ratified Phase 1 record."""

from __future__ import annotations

import hashlib
import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "exports"
TODAY = date.today().isoformat()
SCHEMA_VERSION = "1.0.0"


def envelope(source_of_truth, status="current", dependencies=None):
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_date": TODAY,
        "source_of_truth": source_of_truth,
        "document_status": status,
        "provenance": "Generated by scripts/generate_exports.py; human-reviewed canon and registers govern.",
        "validation_result": {"status": "not_run", "checked_at": None},
        "unresolved_dependencies": dependencies or [],
    }


def write(name, payload):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def confidence(level, basis):
    return {"level": level, "basis": basis}


def claim(
    statement_id,
    text,
    statement_type,
    evidence_class,
    provenance,
    locator,
    conf,
    external,
    dependencies=None,
    contradiction="none",
    supersedes=None,
):
    return {
        "statement_id": statement_id,
        "statement_text": text,
        "statement_type": statement_type,
        "evidence_class": evidence_class,
        "status": "current",
        "provenance": provenance,
        "source_location": locator,
        "confidence": conf,
        "external_use_status": external,
        "date_last_reviewed": "2026-07-26",
        "dependencies": dependencies or [],
        "contradiction_status": contradiction,
        "supersession": {"supersedes": supersedes or [], "superseded_by": []},
    }


manifest = envelope(
    ["docs/planning/Project Canon.md", "docs/planning/Decision Log.md"],
    status="ratified",
    dependencies=[
        "D-P5",
        "D-P6",
        "D-P7",
        "OQ-03",
        "OQ-04",
        "OQ-08",
        "OQ-14",
        "OQ-15",
        "OQ-17",
        "OQ-18",
        "MA-01",
        "MA-02",
        "MA-07",
        "MA-11",
    ],
)
manifest.update(
    {
        "project_id": "south-andrews-healthcare-mobility-hub",
        "canonical_name": "South Andrews Healthcare and Mobility Hub",
        "canonical_address": "901–917 South Andrews Avenue, Fort Lauderdale, Florida",
        "address_aliases": [
            {
                "address": "901–917 S Andrews Avenue",
                "use": "abbreviated canonical identity",
            },
            {
                "address": "901–915 S Andrews Avenue",
                "use": "historical/source-specific",
            },
            {"address": "917 S Andrews Avenue", "use": "appraisal/parcel-specific"},
            {
                "address": "905 S Andrews Avenue",
                "use": "Native Realty filename only; report text uses assemblage address",
            },
        ],
        "property_status": "prospective_acquisition",
        "ownership_status": "not_owned_by_sponsor",
        "site_control_status": "not_documented",
        "project_status": "evidence_and_partner_validation",
        "anchor_thesis": "healthcare",
        "mobility_role": "enabling_infrastructure",
        "base_case_feasible": False,
        "base_case_feasibility_basis": "Convergent planning-level model outputs from S2 and S3; incompatible program bases remain unresolved.",
        "opening_offer_usd": 8000000,
        "opening_offer_classification": "adopted_strategy",
        "offer_authority_status": "unresolved",
        "maximum_price_status": "unresolved",
        "walk_away_price_status": "unresolved",
        "adopted_scheme": None,
        "active_scenarios": ["6_story", "8_story"],
        "ratified_decisions": ["D-P1", "D-P2", "D-P8", "D-P9", "D-P11", "D-P12"],
        "pending_decisions": ["D-P3", "D-P4", "D-P5", "D-P6", "D-P7", "D-P10"],
        "pending_studies": [
            "architectural_parking_test_fit",
            "zoning_verification",
            "fpl_capacity_load",
            "mob_clinical_rent_validation",
            "tax_credit_advice",
            "environmental",
            "survey_title",
            "stormwater_flood",
            "traffic_access",
            "parking_operations",
            "partner_demand_validation",
        ],
        "external_use_restrictions": [
            "no ownership or site-control implication",
            "no partner or government commitment implication",
            "no adopted design or story count",
            "no utility-capacity claim",
            "no unresolved rent or tax-credit underwriting",
            "no speculative AV revenue in governance-clean base case",
            "do not omit negative feasibility finding",
        ],
        "last_owner_ratification_date": "2026-07-26",
    }
)
write("project-manifest.json", manifest)

decisions = [
    {
        "decision_id": "D-P1",
        "title": "Land-offer mandate",
        "exact_decision_statement": "Working opening offer is $8,000,000 as an acquisition-strategy input, not proof of value or offer-submission authority. Negotiating authority, maximum price, walk-away price, and final conditions remain unresolved pending diligence.",
        "status": "ratified",
        "decision_date": "2026-07-26",
        "decision_maker": "Owner",
        "evidence_or_rationale": ["Owner instruction", "S2 Assumptions!B18", "S3 Assumptions!D7", "S8 p.7"],
        "affected_documents": ["Project Canon", "Master Assumption Register", "project manifest"],
        "superseded_decisions": [],
        "review_trigger": "New diligence or written transaction/price authority",
    },
    {
        "decision_id": "D-P2",
        "title": "Project thesis",
        "exact_decision_statement": "Healthcare is the anchor; mobility, parking, charging, energy, data, and AV systems are enabling or optional; governance-clean base feasibility excludes speculative optional revenue.",
        "status": "ratified",
        "decision_date": "2026-07-26",
        "decision_maker": "Owner",
        "evidence_or_rationale": ["Owner instruction", "AGENTS.md current project scope"],
        "affected_documents": ["Project Canon", "scenario register", "future models"],
        "superseded_decisions": ["D-H1", "D-H3 within their active-scope implications"],
        "review_trigger": "Owner thesis change or contractually supported optional revenue",
    },
    {
        "decision_id": "D-P8",
        "title": "Records hygiene",
        "exact_decision_statement": "Adopt controlled lifecycle, provenance, verification, scenario, and external-use statuses while preserving lineage.",
        "status": "ratified",
        "decision_date": "2026-07-26",
        "decision_maker": "Owner",
        "evidence_or_rationale": ["Owner instruction"],
        "affected_documents": ["metadata schema", "registers", "exports", "archive map"],
        "superseded_decisions": [],
        "review_trigger": "Status-vocabulary amendment",
    },
    {
        "decision_id": "D-P9",
        "title": "Governance succession",
        "exact_decision_statement": "AGENTS.md and current docs/governance are operative; recovered prior governance is historical evidence pending reconciliation and express owner action.",
        "status": "ratified",
        "decision_date": "2026-07-26",
        "decision_maker": "Owner",
        "evidence_or_rationale": ["Owner instruction", "MA-01", "MA-02"],
        "affected_documents": ["AGENTS.md", "governance set", "planning references"],
        "superseded_decisions": [],
        "review_trigger": "Authenticated prior governance recovered",
    },
    {
        "decision_id": "D-P11",
        "title": "Repository refactor Phase 1",
        "exact_decision_statement": "Authorize Phase 1 architecture, records, schemas, exports, templates, links, archive maps, and validation without altering sources/models or resolving economic/program choices.",
        "status": "ratified",
        "decision_date": "2026-07-26",
        "decision_maker": "Owner",
        "evidence_or_rationale": ["Owner instruction", "Repository Refactoring Plan"],
        "affected_documents": ["repository architecture"],
        "superseded_decisions": [],
        "review_trigger": "Phase 2, source operation, model-vNext, or external materials",
    },
    {
        "decision_id": "D-P12",
        "title": "Canonical address",
        "exact_decision_statement": "Use 901–917 South Andrews Avenue, Fort Lauderdale, Florida as canonical identity address while preserving parcel/source-specific addresses.",
        "status": "ratified",
        "decision_date": "2026-07-26",
        "decision_maker": "Owner",
        "evidence_or_rationale": ["Owner instruction", "source address reconciliation"],
        "affected_documents": ["Project Canon", "manifest", "future communications"],
        "superseded_decisions": [],
        "review_trigger": "Controlling title/survey changes identity",
    },
]
for did, title, predicate in [
    ("D-P3", "Convertible-structure scope", "test-fit, engineering, code, and GC pricing"),
    ("D-P4", "Optional-revenue/model treatment", "model-vNext authorization and contractual support"),
    ("D-P5", "Program and floor-plate basis", "architectural/parking test-fit"),
    ("D-P6", "Medical-office and clinical rent basis", "independent rent study"),
    ("D-P7", "Tax-credit treatment", "qualified tax advice"),
    ("D-P10", "Final story selection", "program, entitlement, economics, and model-vNext"),
]:
    decisions.append(
        {
            "decision_id": did,
            "title": title,
            "exact_decision_statement": "No decision has been made.",
            "status": "pending",
            "decision_date": None,
            "decision_maker": "Owner",
            "evidence_or_rationale": [f"Pending {predicate}"],
            "affected_documents": ["Project Canon and downstream artifacts"],
            "superseded_decisions": [],
            "review_trigger": predicate,
        }
    )
payload = envelope(
    ["docs/planning/Decision Log.md", "docs/decisions/"],
    status="ratified",
    dependencies=["D-P5", "D-P6", "D-P7", "D-P10"],
)
payload["decisions"] = decisions
write("decisions-register.json", payload)

claims = [
    claim("CAN-001", "The canonical project name is South Andrews Healthcare and Mobility Hub.", "owner_decision", "verified_fact", ["D-G1"], ["AGENTS.md"], confidence("high", "Explicit repository governance"), "external_eligible"),
    claim("CAN-002", "The canonical identity address is 901–917 South Andrews Avenue, Fort Lauderdale, Florida.", "owner_decision", "current_working_assumption", ["D-P12"], ["docs/decisions/D-P12-canonical-address.md"], confidence("high", "Explicit owner-selected identity string"), "approved_with_caveat", ["title/survey confirmation"]),
    claim("CAN-003", "The sponsor does not currently own the property.", "owner_decision", "verified_fact", ["D-G3", "D-P1"], ["AGENTS.md", "docs/decisions/D-P1-land-offer-mandate.md"], confidence("high", "Explicit owner/governance status"), "external_eligible"),
    claim("CAN-004", "The $8,000,000 opening-offer figure is a strategy input, not proof of value or transaction authority.", "adopted_strategy", "current_working_assumption", ["D-P1"], ["docs/decisions/D-P1-land-offer-mandate.md"], confidence("high", "Explicit owner decision within limited scope"), "internal_only", ["negotiating authority", "diligence"]),
    claim("CAN-010", "Healthcare is the project anchor.", "adopted_strategy", "current_working_assumption", ["D-P2"], ["docs/decisions/D-P2-project-thesis.md"], confidence("high", "Explicit owner strategy"), "approved_with_caveat", ["market validation", "test-fit", "entitlement", "economics"]),
    claim("CAN-011", "Mobility, energy, charging, data, and AV systems are enabling or optional infrastructure.", "adopted_strategy", "current_working_assumption", ["D-P2"], ["docs/decisions/D-P2-project-thesis.md"], confidence("high", "Explicit owner strategy"), "approved_with_caveat", ["engineering", "utility capacity", "economics"]),
    claim("CAN-012", "A governance-clean base case excludes speculative optional AV and similar revenue.", "owner_decision", "current_working_assumption", ["D-P2"], ["docs/decisions/D-P2-project-thesis.md"], confidence("high", "Explicit owner rule"), "approved_with_caveat", ["S3 successor-model correction"], "known_model_conflict"),
    claim("CAN-013", "Nearby Broward Health expansion may create complementary healthcare-related demand, but extent, timing, and rent implications are not independently validated.", "source_derived_claim", "source_derived_but_not_independently_verified", ["S4", "S5", "MA-07"], ["S4/S5 citing missing market study"], confidence("low", "Underlying study is missing"), "blocked_pending_resolution", ["MA-07", "MB-07", "partner demand validation"]),
    claim("CAN-020", "S2 reports 3.83%/4.02% yield on cost, approximately -$27.7M/-$33.9M development profit, and approximately 1.2%/1.9% ten-year unlevered IRR.", "model_output", "model_output", ["S2"], ["Returns!B13:B31"], confidence("high", "Recorded workbook outputs"), "approved_with_caveat", ["D-P5", "D-P6", "D-P7"]),
    claim("CAN-021", "S3 reports 3.83%/4.07% core yield on cost, approximately $1.89M-$3.23M annual support gaps, and approximately -$28.1M to -$47.7M value gaps.", "model_output", "model_output", ["S3"], ["Financing & Returns!D21:E28"], confidence("high", "Recorded workbook outputs"), "approved_with_caveat", ["D-P5", "D-P6", "D-P7", "OQ-22"]),
    claim("CAN-022", "Both current models indicate that the presently modeled base project at an $8,000,000 land basis does not meet their respective modeled institutional return requirements.", "model_output", "model_output", ["S2", "S3"], ["S2 Returns", "S3 Financing & Returns"], confidence("high", "Independent models converge on the conclusion"), "approved_with_caveat", ["incompatible program bases"]),
    claim("CAN-030", "Convertible parking, universal grid, and conversion-friendly ramp treatment are planning strategies.", "adopted_strategy", "recommendation", ["D-P2", "S4"], ["Project Canon §4"], confidence("medium", "Adopted intent but untested"), "internal_only", ["D-P3", "test-fit", "engineering", "code", "pricing"]),
    claim("CAN-031", "Approximately 40 initial chargers is a planning placeholder.", "working_assumption", "current_working_assumption", ["S2", "S3"], ["Master Assumption Register CST-09"], confidence("medium", "Models converge on total but not mix"), "internal_only", ["OQ-21", "MB-03"]),
    claim("CAN-032", "Medical co-working is an uncommitted program concept.", "scenario", "current_working_assumption", ["S4"], ["Project Canon §4"], confidence("low", "No operator commitment or demand validation"), "blocked_pending_resolution", ["OQ-08", "MB-08"]),
    claim("CAN-033", "Phasing is an adopted planning strategy subject to validation.", "adopted_strategy", "recommendation", ["D-P2", "S4"], ["Project Canon §4"], confidence("medium", "Program logic only"), "internal_only", ["test-fit", "financing", "operator input", "economics"]),
    claim("CAN-034", "Roof garden, solar/BESS, small data room, and AV staging are unresolved optional concepts.", "scenario", "current_working_assumption", ["S2", "S3", "S4"], ["Project Canon §4"], confidence("low", "Sizing and feasibility unresolved"), "internal_only", ["MB-03", "test-fit", "engineering", "economics"]),
]
payload = envelope(
    ["docs/planning/Project Canon.md", "docs/governance/CLAIMS_AND_EVIDENCE_POLICY.md"],
    status="ratified",
    dependencies=sorted({d for item in claims for d in item["dependencies"]}),
)
payload["claims"] = claims
write("claims-register.json", payload)

assumptions = [
    ("ACQ-01", 8000000, "USD", "acquisition", "current_working_assumption", "ratified_limited_scope", ["S2", "S3"], ["project_wide"], "D-P1", "high", "internal_only"),
    ("ACQ-02", None, "USD", "acquisition", "open_question", "unresolved", ["D-P1", "OQ-20"], ["project_wide"], "later owner price decision", "high", "blocked_pending_resolution"),
    ("PRG-01A", 35000, "SF/floor", "program", "current_working_assumption", "scenario", ["S2"], ["basis_A_35k"], "D-P5", "high", "internal_only"),
    ("PRG-01B", {"ground_parking": 28000, "office": 24000}, "SF/floor", "program", "current_working_assumption", "scenario", ["S3", "S8"], ["basis_B_28k24k"], "D-P5", "high", "internal_only"),
    ("REV-01A", 36, "USD/RSF/year", "rent", "source_derived_but_not_independently_verified", "scenario", ["S2"], ["basis_A_35k"], "D-P6", "high", "blocked_pending_resolution"),
    ("REV-01B", 50, "USD/RSF/year", "rent", "current_working_assumption", "scenario", ["S3"], ["basis_B_28k24k"], "D-P6", "high", "blocked_pending_resolution"),
    ("CST-14A", 0.30, "fraction", "tax_credit", "current_working_assumption", "scenario", ["S2"], ["basis_A_35k"], "D-P7", "high", "blocked_pending_resolution"),
    ("CST-14B", 0, "fraction", "tax_credit", "current_working_assumption", "scenario", ["S3"], ["basis_B_28k24k"], "D-P7", "high", "blocked_pending_resolution"),
    ("EXT-01A", 0.0625, "fraction", "exit_cap", "current_working_assumption", "scenario", ["S2"], ["basis_A_35k"], "later owner underwriting decision", "high", "blocked_pending_resolution"),
    ("EXT-01B", 0.0725, "fraction", "exit_cap", "current_working_assumption", "scenario", ["S3"], ["basis_B_28k24k"], "later owner underwriting decision", "high", "blocked_pending_resolution"),
    ("REV-06", 0, "USD/year", "optional_av_revenue", "current_working_assumption", "ratified_base_case_rule", ["D-P2"], ["governance_clean_base_case"], None, "high", "approved_with_caveat"),
    ("CST-09", 40, "chargers", "charging", "current_working_assumption", "planning_placeholder", ["S2", "S3"], ["project_wide"], "later owner decision after MB-03", "medium", "internal_only"),
]
assumption_records = []
for aid, value, unit, category, evidence, status, source, scenarios, decision, sensitivity, external in assumptions:
    assumption_records.append(
        {
            "assumption_id": aid,
            "value_or_range": value,
            "unit": unit,
            "category": category,
            "evidence_class": evidence,
            "status": status,
            "model_usage": ["future model-vNext only after authorization"],
            "scenario_association": scenarios,
            "source": source,
            "external_use_restriction": external,
            "owner_decision_requirement": decision,
            "sensitivity_importance": sensitivity,
        }
    )
payload = envelope(
    ["docs/planning/Master Assumption Register.md"],
    dependencies=["D-P5", "D-P6", "D-P7", "OQ-18", "OQ-21"],
)
payload["assumptions"] = assumption_records
write("assumptions-register.json", payload)

scenarios = [
    ("6_story", "Six-story scenario", "current", None, "healthcare", ["S2", "S3"], ["basis conflict unresolved"], None),
    ("8_story", "Eight-story scenario", "current", None, "healthcare", ["S2", "S3"], ["basis conflict unresolved"], None),
    ("basis_A_35k", "35,000 SF plate basis", "current", "basis_A_35k", "healthcare", ["S2"], ["basis_B_28k24k"], None),
    ("basis_B_28k24k", "28,000/24,000 SF plate basis", "current", "basis_B_28k24k", "healthcare", ["S3", "S8"], ["basis_A_35k"], None),
    ("healthcare_led", "Healthcare-led thesis", "current", "tbd_test_fit", "healthcare", ["D-P2"], [], "D-P2"),
    ("mobility_led_historical", "Mobility-led historical concept", "rejected_scenario", None, "mobility", ["S2", "MA-12"], [], "D-P2"),
    ("car_rental_fleet_hub", "Car-rental fleet hub", "rejected_scenario", None, "rental_car", ["S8"], [], "D-P2"),
    ("seller_agora", "Seller Agora retail concept", "historical", None, "seller_retail", ["S6"], [], None),
    ("residential_historical", "Residential historical scenario", "rejected_scenario", None, "residential", ["S8"], [], "D-P2"),
    ("hotel_historical", "Hotel historical scenario", "rejected_scenario", None, "hotel", ["S8"], [], "D-P2"),
]
scenario_records = [
    {
        "scenario_id": sid,
        "title": title,
        "scenario_status": status,
        "program_basis": basis,
        "thesis": thesis,
        "source": source,
        "incompatibilities": incompatible,
        "adoption_decision": decision,
        "external_use_status": "internal_only" if status != "historical" else "blocked_pending_resolution",
    }
    for sid, title, status, basis, thesis, source, incompatible, decision in scenarios
]
payload = envelope(
    ["docs/planning/Project Canon.md", "docs/planning/Current Development Program.md"],
    dependencies=["D-P5", "D-P10", "MB-02"],
)
payload["scenarios"] = scenario_records
write("scenario-register.json", payload)

open_items = {
    "OQ-01": ("Healthcare vs mobility thesis", "closed", "D-P2"),
    "OQ-02": ("Achievable parking/program split", "open", "MB-02"),
    "OQ-03": ("Zoning/height/parking verification", "open", "MB-01"),
    "OQ-04": ("FPL transformer capacity", "open", "MB-03"),
    "OQ-05": ("Traffic/access/queuing", "open", "MB-04"),
    "OQ-06": ("Stormwater/flood design", "open", "MB-05"),
    "OQ-07": ("Geotechnical conditions", "open", "MB-06"),
    "OQ-08": ("Medical co-working operator/terms", "open", "MB-08"),
    "OQ-09": ("Title/easement/survey", "open", "MB-10"),
    "OQ-10": ("Convertibility premium", "open", "MB-16"),
    "OQ-11": ("Final story selection", "open", "D-P10"),
    "OQ-12": ("Agora branding reconciliation", "closed", "D-P8"),
    "OQ-13": ("Environmental scope/findings", "open", "MB-11"),
    "OQ-14": ("Program/floor-plate basis", "open", "D-P5"),
    "OQ-15": ("Office/clinical rent basis", "open", "D-P6"),
    "OQ-16": ("Parking revenue basis", "open", "MB-09"),
    "OQ-17": ("Tax-credit treatment", "open", "D-P7"),
    "OQ-18": ("Exit cap/hurdle basis", "open", "later owner decision"),
    "OQ-19": ("Governance succession", "closed", "D-P9"),
    "OQ-20": ("Negotiating authority/ceiling/walk-away", "partially_resolved", "later owner decision"),
    "OQ-21": ("Charger mix", "open", "MB-03"),
    "OQ-22": ("S3 AV revenue in base NOI", "open", "model-vNext"),
    "OQ-23": ("Canonical address", "closed", "D-P12"),
}
payload = envelope(
    ["docs/planning/Open Questions.md"],
    dependencies=[key for key, value in open_items.items() if value[1] != "closed"],
)
payload["open_questions"] = [
    {"question_id": key, "question": value[0], "status": value[1], "resolve_via": value[2]}
    for key, value in open_items.items()
]
write("open-questions.json", payload)

risks = [
    ("R-01", "Base-case return gap", "high", "high", "Preserve finding; resolve evidence/program/land basis before model-vNext."),
    ("R-02", "Program/floor-plate conflict", "high", "high", "Architectural/parking test-fit and D-P5."),
    ("R-03", "Unvalidated rent basis", "high", "high", "Independent MOB/clinical rent study and D-P6."),
    ("R-04", "Utility capacity unknown", "high", "high", "FPL/load study."),
    ("R-05", "Entitlement/height path unverified", "medium", "high", "Zoning Verification Letter and City review."),
    ("R-06", "No documented partner commitments", "high", "high", "Prospective language; retain evidence; no underwriting without contract."),
    ("R-07", "Environmental/title/survey gaps", "medium", "high", "Recover records and commission diligence."),
    ("R-08", "Tax-credit treatment unresolved", "medium", "high", "Qualified tax advice and D-P7."),
    ("R-09", "Optional AV revenue contaminates S3 base NOI", "high", "medium", "Caveat current output; correct only in authorized successor model."),
]
payload = envelope(
    ["docs/planning/Risk Register.md", "docs/planning/Project Canon.md"],
    dependencies=["D-P5", "D-P6", "D-P7", "MB-01", "MB-02", "MB-03", "MB-07", "MB-11"],
)
payload["risks"] = [
    {"risk_id": rid, "description": desc, "probability": probability, "impact": impact, "mitigation": mitigation, "status": "open"}
    for rid, desc, probability, impact, mitigation in risks
]
write("risks-register.json", payload)

source_specs = [
    ("S1", "sources/current/South_Andrews_Corrected_Assumptions.md", "current", "owner_provided", "tier_2", "Corrected assumptions and explicit status/corrections"),
    ("S2", "sources/current/South Andrews 6v8 Story Model.xlsx", "current", "owner_provided", "tier_3", "6-/8-story model within its stated 35k plate basis"),
    ("S3", "sources/current/South_Andrews_8M_Construction_Feasibility.xlsx", "current", "owner_provided", "tier_4", "Feasibility model within its stated 28k/24k basis"),
    ("S4", "sources/current/Andrews ODP with Dashboard.docx", "current", "owner_provided", "subordinate_context", "Institutional program logic; historical name and missing dependencies caveated"),
    ("S5", "sources/legacy/Institutional Development Prospectus Vol0.docx", "legacy", "owner_provided", "tier_8", "Legacy structure/tone and reverified evidence only"),
    ("S6", "sources/reference/Andrew’s Appraisal.pdf", "reference", "seller_provided", "tier_7", "Third-party appraisal and site facts within professional scope"),
    ("S7", "sources/reference/Appraisal Valuation .xlsx", "reference", "third_party", "tier_7", "Analyst valuation context; different program"),
    ("S8", "sources/reference/NativeRealty_905 S Andrews - Development Feasibility & Massing Study.pdf", "reference", "third_party", "tier_7", "Buyer-side zoning/massing/offer context; car-rental thesis rejected"),
]
source_records = []
for sid, relative, source_class, provenance, tier, scope in source_specs:
    path = ROOT / relative
    source_records.append(
        {
            "source_id": sid,
            "exact_path": relative,
            "format": path.suffix.lower().lstrip("."),
            "source_class": source_class,
            "provenance": provenance,
            "authority_tier": tier,
            "scope": scope,
            "integrity_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "byte_size": path.stat().st_size,
            "status": "current" if source_class == "current" else source_class,
            "dependencies": [],
        }
    )
payload = envelope(
    ["docs/planning/Source Inventory.md", "docs/planning/Source Authority Register.md"],
    dependencies=["MA-01", "MA-02", "MA-07", "MA-10", "MA-11", "MA-13"],
)
payload["sources"] = source_records
write("source-register.json", payload)

missing_docs = [
    ("MA-01", "Prior Project Constitution", "missing_but_expected_to_exist"),
    ("MA-02", "Prior Project Decision Log", "missing_but_expected_to_exist"),
    ("MA-03", "Prior README document hierarchy", "missing_but_expected_to_exist"),
    ("MA-04", "Design Standards", "missing_but_expected_to_exist"),
    ("MA-05", "Original Open Questions file", "missing_but_expected_to_exist"),
    ("MA-06", "Underwriting Standards", "missing_but_expected_to_exist"),
    ("MA-07", "Healthcare Market & HBU Analysis / market study", "missing_but_expected_to_exist"),
    ("MA-08", "Feasibility & Benchmark Study", "missing_but_expected_to_exist"),
    ("MA-09", "Site Intelligence Report", "missing_but_expected_to_exist"),
    ("MA-10", "2015 boundary survey", "missing_but_expected_to_exist"),
    ("MA-11", "Electrical load model", "missing_but_expected_to_exist"),
    ("MA-12", "Andrews_Context.md", "missing_but_expected_to_exist"),
    ("MA-13", "Phase I and II environmental reports", "missing_but_expected_to_exist"),
    ("MA-14", "Highland Contractors estimate", "missing_but_expected_to_exist"),
    ("MA-15", "AEI zoning report", "missing_but_expected_to_exist"),
    ("MA-16", "Operational/Site/Feasibility studies cited by S2", "partially_represented_in_another_document"),
    ("MA-17", "Plan 3 session record", "missing_but_expected_to_exist"),
    ("MA-18", "Current listing/offer correspondence", "missing_but_expected_to_exist"),
]
studies = [
    ("MB-01", "Zoning verification", "not_yet_commissioned"),
    ("MB-02", "Architectural and parking test-fit", "not_yet_commissioned"),
    ("MB-03", "FPL capacity/electrical load study", "not_yet_commissioned"),
    ("MB-04", "Traffic and access study", "not_yet_commissioned"),
    ("MB-05", "Stormwater/flood engineering", "not_yet_commissioned"),
    ("MB-06", "Geotechnical work", "not_yet_commissioned"),
    ("MB-07", "MOB/clinical rent study", "not_yet_commissioned"),
    ("MB-08", "Partner/operator demand validation", "not_yet_commissioned"),
    ("MB-09", "Parking operations study", "not_yet_commissioned"),
    ("MB-10", "Updated survey/title/legal review", "not_yet_commissioned"),
    ("MB-11", "Phase I ESA and Phase II if applicable", "not_yet_commissioned"),
    ("MB-12", "Insurance validation", "not_yet_commissioned"),
    ("MB-13", "Tax-credit memorandum", "not_yet_commissioned"),
    ("MB-14", "Grant/TIF/public-support research", "not_yet_commissioned"),
    ("MB-15", "AV/operator market sounding", "not_yet_commissioned"),
    ("MB-16", "Convertibility cost validation", "not_yet_commissioned"),
]
payload = envelope(
    ["docs/planning/Missing Research Register.md"],
    dependencies=[item[0] for item in missing_docs + studies],
)
payload["missing_research"] = [
    {"item_id": item_id, "title": title, "status": status, "record_type": "missing_document"}
    for item_id, title, status in missing_docs
] + [
    {"item_id": item_id, "title": title, "status": status, "record_type": "pending_study"}
    for item_id, title, status in studies
]
write("missing-research.json", payload)

payload = envelope(
    ["docs/planning/Project Canon.md", "docs/planning/Master Assumption Register.md"],
    dependencies=["D-P5", "D-P6", "D-P7", "OQ-18", "OQ-22"],
)
payload["metrics"] = {
    "site_area_sf": {"value": 38207, "classification": "corroborated_fact", "external_use_status": "approved_with_caveat"},
    "opening_offer_usd": {"value": 8000000, "classification": "adopted_strategy", "external_use_status": "internal_only"},
    "base_case_feasible": {"value": False, "classification": "model_output", "external_use_status": "approved_with_caveat"},
    "s2_yield_on_cost": {"6_story": 0.0383, "8_story": 0.0402, "classification": "model_output", "program_basis": "basis_A_35k"},
    "s3_core_yield_on_cost": {"6_story": 0.0383, "8_story": 0.0407, "classification": "model_output", "program_basis": "basis_B_28k24k"},
    "adopted_story_count": None,
    "adopted_floor_plate": None,
}
write("key-metrics.json", payload)

payload = envelope(
    ["docs/planning/Executive Planning Summary.md", "docs/planning/Project Canon.md"],
    status="ratified",
    dependencies=["D-P5", "D-P6", "D-P7", "D-P10"],
)
payload["executive_status"] = {
    "canon_ratified": True,
    "phase_1_completed": True,
    "property_status": "prospective_acquisition",
    "ownership_status": "not_owned_by_sponsor",
    "feasibility_status": "does_not_meet_current_modeled_institutional_requirements",
    "adopted_thesis": "healthcare_anchor",
    "mobility_role": "enabling_or_optional",
    "adopted_scheme": None,
    "next_gate": "evidence recovery and commissioned diligence",
}
write("executive-status.json", payload)

print(f"Generated 11 exports in {OUT}")
